"""Table and figure production, and the provenance header every output carries.

Every artefact written by this module records the git commit, the random seed,
and an explicit statement that the contents are simulated.  That is a research
integrity requirement, not decoration: a table of simulated numbers that is
separated from its provenance is indistinguishable from a table of
measurements.
"""
from __future__ import annotations

import json
import os
import subprocess
from dataclasses import asdict, is_dataclass
from typing import Dict, Optional, Sequence

import numpy as np
import pandas as pd

from .config import Config, DEFAULT

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
TABLES = os.path.join(ROOT, "results", "tables")
FIGURES = os.path.join(ROOT, "results", "figures")
RAW = os.path.join(ROOT, "results", "raw")

SIMULATED_BANNER = (
    "SIMULATED DATA -- generated by the opcem digital twin. "
    "These values are not measurements and were not obtained from any "
    "physical microscope, nanoreactor or mass spectrometer."
)


def git_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", ROOT, "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return "unknown"


def ensure_dirs() -> None:
    for d in (TABLES, FIGURES, RAW):
        os.makedirs(d, exist_ok=True)


def save_table(df: pd.DataFrame, name: str, caption: str,
               cfg: Config = DEFAULT, seed: Optional[int] = None,
               float_fmt: str = "%.4g") -> Dict[str, str]:
    """Write a table as CSV (with a provenance header) and as markdown."""
    ensure_dirs()
    csv_path = os.path.join(TABLES, f"{name}.csv")
    md_path = os.path.join(TABLES, f"{name}.md")
    header = [f"# {name}", f"# {caption}", f"# {SIMULATED_BANNER}",
              f"# git={git_sha()} seed={seed if seed is not None else cfg.seed}"]
    with open(csv_path, "w") as fh:
        fh.write("\n".join(header) + "\n")
        df.to_csv(fh, index=False, float_format=float_fmt)
    with open(md_path, "w") as fh:
        fh.write(f"**{name}** — {caption}\n\n")
        fh.write(f"_{SIMULATED_BANNER}_\n\n")
        fh.write(df.to_markdown(index=False, floatfmt=".4g"))
        fh.write(f"\n\n<sub>git={git_sha()} "
                 f"seed={seed if seed is not None else cfg.seed}</sub>\n")
    return {"csv": csv_path, "md": md_path}


def save_json(obj, name: str, cfg: Config = DEFAULT,
              seed: Optional[int] = None) -> str:
    ensure_dirs()
    path = os.path.join(RAW, f"{name}.json")
    payload = {"_provenance": {"simulated": True, "banner": SIMULATED_BANNER,
                               "git": git_sha(),
                               "seed": seed if seed is not None else cfg.seed},
               "data": _to_jsonable(obj)}
    with open(path, "w") as fh:
        json.dump(payload, fh, indent=2)
    return path


def _to_jsonable(o):
    if is_dataclass(o) and not isinstance(o, type):
        return _to_jsonable(asdict(o))
    if isinstance(o, dict):
        return {str(k): _to_jsonable(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_to_jsonable(v) for v in o]
    if isinstance(o, np.ndarray):
        return _to_jsonable(o.tolist())
    if isinstance(o, (np.floating, float)):
        v = float(o)
        return None if not np.isfinite(v) else v
    if isinstance(o, (np.integer, int)):
        return int(o)
    if isinstance(o, (np.bool_, bool)):
        return bool(o)
    if isinstance(o, pd.DataFrame):
        return _to_jsonable(o.to_dict(orient="records"))
    return o


# --------------------------------------------------------------------------- #
# figure style
# --------------------------------------------------------------------------- #
# Categorical palette, validated with the data-viz six-checks validator in
# light mode against surface #fcfcfb: all checks pass (worst adjacent CVD
# deltaE 9.2 deutan, worst adjacent normal-vision deltaE 27.6).  The aqua slot
# carries a contrast warning below 3:1, so the relief rule applies: every
# figure ships a legend and a companion table in results/tables.  Manuscript
# figures are print artefacts, so only the light-mode steps are used.
PALETTE = {
    "truth": "#2a78d6",        # slot 1, blue
    "observed": "#eb6834",     # slot 2, orange
    "corrected": "#1baf7a",    # slot 3, aqua  (labelled, see relief rule)
    "accent": "#4a3aa7",       # slot 7, violet
    "uncorrected": "#8a8a85",  # neutral ink, not a categorical slot
    "neutral": "#52514e",
    "surface": "#fcfcfb",
    "grid": "#d8d8d3",
}


def style() -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({
        "figure.dpi": 160, "savefig.dpi": 160,
        "font.size": 8.5, "axes.titlesize": 9.5, "axes.labelsize": 8.5,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.grid": True, "grid.alpha": 0.25, "grid.linewidth": 0.5,
        "legend.frameon": False, "legend.fontsize": 7.5,
        "lines.linewidth": 1.3, "figure.constrained_layout.use": True,
        "savefig.bbox": "tight", "axes.axisbelow": True,
    })


def save_figure(fig, name: str, caption: str) -> Dict[str, str]:
    """Write the figure plus a sidecar caption that carries the banner."""
    ensure_dirs()
    png = os.path.join(FIGURES, f"{name}.png")
    pdf = os.path.join(FIGURES, f"{name}.pdf")
    fig.savefig(png)
    fig.savefig(pdf)
    with open(os.path.join(FIGURES, f"{name}.caption.md"), "w") as fh:
        fh.write(f"**{name}** — {caption}\n\n_{SIMULATED_BANNER}_\n\n"
                 f"<sub>git={git_sha()}</sub>\n")
    return {"png": png, "pdf": pdf}
